#!/usr/bin/env node

import fs from 'fs'
import { execSync } from 'child_process'

const force = process.argv.includes('--force')

if (execSync('git status --porcelain', { encoding: 'utf8' }).trim() && !force) {
  console.error('Error: Git working tree is dirty. Please commit or stash your changes first, or re-run with --force.')
  process.exit(1)
}

const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'))

pkg.pnpm.overrides = pkg.pnpm.overrides || {}
// pkg.pnpm.overrides["nostr-editor"] = "link:../nostr-editor"
// pkg.pnpm.overrides["@pomade/core"] = "link:../pomade/packages/core"
// pkg.pnpm.overrides["nostr-signer-capacitor-plugin"] = "link:../nostr-signer-capacitor-plugin"

fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n')

execSync('pnpm i', { stdio: 'inherit' })

execSync('git checkout -f pnpm-lock.yaml', { stdio: 'inherit' })
execSync('git checkout -f package.json', { stdio: 'inherit' })
